version: "3.5"

services:
  app:
    image: ${IMAGE_REPOSITORY:?}:latest
    container_name: veryneatfastapiapp
    restart: "no"
    environment:
      # fastapi settings
      WEBSERVER_PORT: ${WEBSERVER_PORT:?}
      RELOAD: ${RELOAD:?}
      DEBUG: ${DEBUG:?}
      WORKERS_COUNT: ${WORKERS_COUNT:?}
    # volumes:
    #   - staticfiles:${DOCKER_APP_CODE:?}/staticfiles/
    # healthcheck:
    #   test: curl -f -s -S http://localhost:8080 || exit 1
    #   interval: 30s
    #   timeout: 120s
    #   retries: 10
    expose: 
      - 5700
    ports: 
      - "${WEBSERVER_PORT:?}:${WEBSERVER_PORT:?}"
    entrypoint: ["python", "veryneatapp/run.py"]